package com.eafb
fun main() {
    check(CatalogCardPolicy.hasPoster("/poster.jpg"))
    check(!CatalogCardPolicy.hasPoster(null))
    check(!CatalogCardPolicy.hasPoster(""))
    check(!CatalogCardPolicy.hasPoster("/"))
    check(!CatalogCardPolicy.hasPoster("https://bad.invalid/poster"))
    check(CatalogCardPolicy.hasNext(1,19,4))
    check(CatalogCardPolicy.hasNext(3,1,4))
    check(!CatalogCardPolicy.hasNext(4,20,4))
    check(!CatalogCardPolicy.hasNext(1,0,4))
    check(!CatalogCardPolicy.hasNext(20,20,30))
    check(!CatalogCardPolicy.hasNext(1,19,0))
    check(CatalogCardPolicy.hasNext(1,20,0))
    check(!CatalogCardPolicy.hasNext(0,20,2))
    check(CatalogCardPolicy.bestArtwork("/poster.jpg", "/backdrop.jpg") == "/poster.jpg")
    check(CatalogCardPolicy.bestArtwork(null, "/backdrop.jpg") == "/backdrop.jpg")
    check(CatalogCardPolicy.bestArtwork("", "/backdrop.jpg") == "/backdrop.jpg")
    check(CatalogCardPolicy.bestArtwork("/", "/backdrop.jpg") == "/backdrop.jpg")
    check(CatalogCardPolicy.bestArtwork(null, null) == null)
    check(CatalogCardPolicy.bestArtwork("//evil.example/poster", null) == null)
    check(CatalogCardPolicy.bestArtwork("//evil.example/poster", "/safe.jpg") == "/safe.jpg")
    check(CatalogCardPolicy.collectionArtwork(2,2,null,null,"/selected.jpg") == "/selected.jpg")
    check(CatalogCardPolicy.collectionArtwork(3,2,null,null,"/selected.jpg") == null)
    check(CatalogCardPolicy.collectionArtwork(2,2,"/part.jpg",null,"/selected.jpg") == "/part.jpg")
    check(CatalogCardPolicy.collectionArtwork(2,2,null,"/part-backdrop.jpg","/selected.jpg") == "/part-backdrop.jpg")
    check(CatalogCardPolicy.collectionArtwork(2,2,null,null,"//bad.example/image") == null)
    println("PASS: 25/25 catalog card assertions")
}
